# Generated by Django 5.2.7 on 2025-11-06 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0002_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_at',
            new_name='added_on',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
