# Generated by Django 5.2.7 on 2025-11-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='people_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
