# Generated by Django 5.2.7 on 2025-11-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_travelpackage_people_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
