# Generated by Django 5.2.7 on 2025-11-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_agencyprofile_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='climate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
