# Generated by Django 5.2.7 on 2025-11-11 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_rename_booked_at_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
