# Generated by Django 5.2.7 on 2025-11-12 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='tsender',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agency.booking'),
            preserve_default=False,
        ),
    ]
