# Generated by Django 5.2.7 on 2025-11-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_remove_chatmessage_agency_remove_chatmessage_tsender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
