# Generated by Django 5.2.7 on 2025-11-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_booking_razorpay_order_id_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Paid', 'Paid'), ('Checked-In', 'Checked-In'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
