# Generated by Django 5.2.7 on 2025-11-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
