# Generated by Django 5.2.7 on 2025-11-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_booking_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
