# Generated by Django 5.2.7 on 2025-12-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_booking_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='package_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('couple', 'Couple'), ('friends', 'Friends'), ('group', 'Group')], max_length=20, null=True),
        ),
    ]
